import { DEFAULT_FORMULA_PARAMS } from "@/lib/formula";
import type { RecommendationUserData } from "@/lib/pvr/types";

export const LOCAL_RECOMMENDATION_USER_DATA: RecommendationUserData = {
  movies: [
    {
      id: "local-1",
      title: "Dune: Part Two",
      rating: 9.2,
      genres: ["Science Fiction", "Adventure", "Drama"],
      language: "English",
      director: "Denis Villeneuve",
      castMembers: ["Timothee Chalamet", "Zendaya"],
      date: "2024-03-01",
      ticketCost: 620,
      convenienceFee: 45,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-imax",
      theaterId: "theater-pallasio",
      rewatchId: "rewatch-high",
      releaseDate: "2024-03-01",
    },
    {
      id: "local-2",
      title: "Oppenheimer",
      rating: 9,
      genres: ["Drama", "History", "Thriller"],
      language: "English",
      director: "Christopher Nolan",
      castMembers: ["Cillian Murphy", "Robert Downey Jr."],
      date: "2023-07-21",
      ticketCost: 520,
      convenienceFee: 45,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-imax",
      theaterId: "theater-pallasio",
      rewatchId: "rewatch-high",
      releaseDate: "2023-07-21",
    },
    {
      id: "local-3",
      title: "Jawan",
      rating: 8.1,
      genres: ["Action", "Thriller"],
      language: "Hindi",
      director: "Atlee",
      castMembers: ["Shah Rukh Khan", "Nayanthara"],
      date: "2023-09-08",
      ticketCost: 340,
      convenienceFee: 35,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-2d",
      theaterId: "theater-palassio",
      rewatchId: "rewatch-mid",
      releaseDate: "2023-09-07",
    },
    {
      id: "local-4",
      title: "Leo",
      rating: 7.6,
      genres: ["Action", "Crime", "Thriller"],
      language: "Tamil",
      director: "Lokesh Kanagaraj",
      castMembers: ["Vijay", "Sanjay Dutt"],
      date: "2023-10-19",
      ticketCost: 280,
      convenienceFee: 35,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-2d",
      theaterId: "theater-palassio",
      rewatchId: "rewatch-mid",
      releaseDate: "2023-10-19",
    },
    {
      id: "local-5",
      title: "Spider-Man: Across the Spider-Verse",
      rating: 8.8,
      genres: ["Animation", "Action", "Adventure"],
      language: "English",
      director: "Joaquim Dos Santos",
      castMembers: ["Shameik Moore", "Hailee Steinfeld"],
      date: "2023-06-02",
      ticketCost: 430,
      convenienceFee: 40,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-pxl",
      theaterId: "theater-palassio",
      rewatchId: "rewatch-high",
      releaseDate: "2023-06-02",
    },
    {
      id: "local-6",
      title: "Fast X",
      rating: 5.8,
      genres: ["Action", "Adventure"],
      language: "English",
      director: "Louis Leterrier",
      castMembers: ["Vin Diesel"],
      date: "2023-05-19",
      ticketCost: 460,
      convenienceFee: 40,
      fnbCost: 0,
      otherExpenses: 0,
      passportSavings: 0,
      formatId: "fmt-4dx",
      theaterId: "theater-palassio",
      rewatchId: "rewatch-low",
      releaseDate: "2023-05-19",
    },
  ],
  watchlist: [
    {
      id: "watch-1",
      title: "Dhurandhar The Revenge",
      priority: 2,
      genres: ["Action", "Thriller"],
      releaseDate: null,
      watchedMovieId: null,
    },
    {
      id: "watch-2",
      title: "Avatar",
      priority: 1,
      genres: ["Science Fiction", "Adventure"],
      releaseDate: null,
      watchedMovieId: null,
    },
  ],
  formats: [
    { id: "fmt-2d", name: "2D", weight: 1 },
    { id: "fmt-3d", name: "3D", weight: 1.1 },
    { id: "fmt-imax", name: "IMAX", weight: 1.6 },
    { id: "fmt-imax-laser", name: "IMAX Laser", weight: 1.7 },
    { id: "fmt-4dx", name: "4DX", weight: 1.3 },
    { id: "fmt-pxl", name: "PXL", weight: 1.4 },
    { id: "fmt-atmos", name: "Dolby Atmos", weight: 1.25 },
    { id: "fmt-luxe", name: "LUXE", weight: 1.25 },
    { id: "fmt-insignia", name: "INSIGNIA", weight: 1.35 },
  ],
  theaters: [
    {
      id: "theater-palassio",
      name: "PVR INOX Lucknow Phoenix Palassio",
      city: "Lucknow",
      capabilities: ["IMAX", "PXL", "4DX", "Atmos"],
    },
    {
      id: "theater-lulu",
      name: "PVR Superplex Lulu Lucknow",
      city: "Lucknow",
      capabilities: ["PXL", "LUXE", "Atmos"],
    },
  ],
  theaterRatings: [
    {
      theaterId: "theater-palassio",
      audi: null,
      sound: 5,
      seat: 4,
      screen: 5,
      cleanliness: 4,
    },
    {
      theaterId: "theater-lulu",
      audi: null,
      sound: 4,
      seat: 4,
      screen: 4,
      cleanliness: 4,
    },
  ],
  rewatchOptions: [
    { id: "rewatch-low", value: 1 },
    { id: "rewatch-mid", value: 3 },
    { id: "rewatch-high", value: 5 },
  ],
  formulaParams: DEFAULT_FORMULA_PARAMS,
};
